### ISSUE TITLE
Correct PHP Warning when editing a customer's record

### ISSUE THREAD

**Issue by lat9** [lat9/vat4eu#30]
Seeing logs like
```
[29-Feb-2024 15:28:17 UTC] Request URI: /zc158a/admin158a/index.php?cmd=customers&page=1&cID=1&action=edit, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc158a\admin158a\customers.php(695): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158a\admin158a\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "fieldname" in C:\xampp\htdocs\zc158a\admin158a\customers.php on line 695.
```

**Comment by lat9** [comment]
Noting that, for zc158a, [this](https://github.com/zencart/zencart/commit/52e86970a638f032a1533fd55e5c63768c9d8d6b) Zen Cart core PR must be applied to properly handle errors when a customer's record is to be update ... like if an invalid VAT number is supplied.

This will be hightlighted in the VAT4EU readme.
